// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportDatabase.Model
{
    public partial class Article
    {
        [Key]
        public int ArticleId { get; set; }
        public int AuthorId { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [MaxLength(1)]
        public byte[] SmallPicture { get; set; }
        [StringLength(300)]
        public string MainPicture { get; set; }
        [StringLength(150)]
        public string ShortArticle { get; set; }
        [Column("Article", TypeName = "text")]
        public string Article1 { get; set; }
        [StringLength(100)]
        public string Keywords { get; set; }
        [Column(TypeName = "date")]
        public DateTime? PublicationTime { get; set; }
        [Column(TypeName = "date")]
        public DateTime? LastUpdate { get; set; }
        public int? CategoryId { get; set; }
        public bool? IsGallery { get; set; }
    }
}