// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SportDatabase.Model
{
    public partial class GetWUserResult
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Login { get; set; }
        public DateTime? PasswordExpired { get; set; }
        public int? RoleId { get; set; }
        public string NameRole { get; set; }
    }
}
