// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportDatabase.Model
{
    public partial class LogException
    {
        [Key]
        public int LogExceptionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [Required]
        [StringLength(150)]
        public string Path { get; set; }
        [Required]
        public string Message { get; set; }
        public int UserId { get; set; }
    }
}