// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportDatabase.Model
{
    [Table("LogOperation")]
    public partial class LogOperation
    {
        [Key]
        public int LogOperationId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(25)]
        public string Controller { get; set; }
        [StringLength(25)]
        public string Operation { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        public int? UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("LogOperations")]
        public virtual User User { get; set; }
    }
}