// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportDatabase.Model
{
    public partial class Permission
    {
        [Key]
        public int PermissionId { get; set; }
        public int UserId { get; set; }
        public int? CategoryId { get; set; }
        public int? UserModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Permissions")]
        public virtual User User { get; set; }
    }
}