// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SportDatabase.Model
{
    public class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.Property(e => e.FirstName).IsUnicode(false);

            entity.Property(e => e.LastName).IsUnicode(false);

            entity.Property(e => e.Login).IsUnicode(false);

            entity.Property(e => e.Password).IsFixedLength();
        }
    }
}
