// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportDatabase.Model
{
    public partial class User
    {
        public User()
        {
            Articles = new HashSet<Article>();
            LogExceptions = new HashSet<LogException>();
            LogOperations = new HashSet<LogOperation>();
        }

        [Key]
        public int UserId { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(80)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string Login { get; set; }
        [MaxLength(64)]
        public byte[] Password { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PasswordExpired { get; set; }
        public int? RoleId { get; set; }

        [ForeignKey(nameof(RoleId))]
        [InverseProperty("Users")]
        public virtual Role Role { get; set; }
        [InverseProperty(nameof(Article.Author))]
        public virtual ICollection<Article> Articles { get; set; }
        [InverseProperty(nameof(LogException.User))]
        public virtual ICollection<LogException> LogExceptions { get; set; }
        [InverseProperty(nameof(LogOperation.User))]
        public virtual ICollection<LogOperation> LogOperations { get; set; }
    }
}