// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportDatabase.Model
{
    public partial class WFullArticle
    {
        public int ArticleId { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Title { get; set; }
        [MaxLength(1)]
        public byte[] SmallPicture { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string ShortArticle { get; set; }
        [Column(TypeName = "text")]
        public string Article { get; set; }
        [Column(TypeName = "date")]
        public DateTime? PublicationTime { get; set; }
        [Column(TypeName = "date")]
        public DateTime? LastUpdate { get; set; }
        public bool? IsGallery { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public int? CategoryId { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(80)]
        public string LastName { get; set; }
    }
}