// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportDatabase.Model
{
    public partial class WFullArticle
    {
        [Key]
        public int ArticleId { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Title { get; set; }
        public string Picture { get; set; }
        [Column(TypeName = "text")]
        public string ShortArticle { get; set; }
        public string SourcePicture { get; set; }
        public string SourceArticle { get; set; }
        [Column(TypeName = "text")]
        public string FullArticle { get; set; }
        [Column(TypeName = "date")]
        public DateTime PublicationTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModified { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public int? CategoryId { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(80)]
        public string LastName { get; set; }
    }
}