// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportDatabase.Model
{
    public partial class WListArticle
    {
        [Key]
        public int ArticleId { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Title { get; set; }
        [MaxLength]
        [Column(TypeName = "text")]
        public string Picture { get; set; }
        [Column(TypeName = "text")]
        public string ShortArticle { get; set; }
        [Column(TypeName = "date")]
        public DateTime PublicationTime { get; set; }
        [StringLength(100)]
        public string Keywords { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public int? CategoryId { get; set; }
    }
}