// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace SportDatabase.Model
{
    public partial class WListArticle
    {
        public int ArticleId { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Title { get; set; }
        [MaxLength(1)]
        public byte[] SmallPicture { get; set; }
        [Column(TypeName = "text")]
        public string ShortArticle { get; set; }
        [DefaultValue(typeof(DateTime))]
        [Column(TypeName = "date")]
        public DateTime PublicationTime { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        //[JsonConverter(typeof(IntToStringConverter))]
        public int? CategoryId { get; set; }
    }
}