// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportDatabase.Model
{
    public partial class WUser
    {
        [Key]
        public int UserId { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(80)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string Login { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PasswordExpired { get; set; }
        public int? RoleId { get; set; }
        [StringLength(100)]
        public string NameRole { get; set; }
    }
}