// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using SportDatabase.Model;
using System;

namespace SportDatabase.Context
{
    public class GalleryConfiguration : IEntityTypeConfiguration<Gallery>
    {
        public void Configure(EntityTypeBuilder<Gallery> entity)
        {
            entity.Property(e => e.Path).IsFixedLength();

            entity.HasOne(d => d.Article)
                .WithMany(p => p.Galleries)
                .HasForeignKey(d => d.ArticleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Gallery__Article__44FF419A");
        }
    }
}
