// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using SportDatabase.Model;
using System;

namespace SportDatabase.Context
{
    public class LogOperationConfiguration : IEntityTypeConfiguration<LogOperation>
    {
        public void Configure(EntityTypeBuilder<LogOperation> entity)
        {
            entity.HasOne(d => d.User)
                .WithMany(p => p.LogOperations)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__LogOperat__UserI__4AB81AF0");
        }
    }
}
