// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using SportDatabase.Model;
using System;

namespace SportDatabase.Context
{
    public class WcategoryConfiguration : IEntityTypeConfiguration<WCategory>
    {
        public void Configure(EntityTypeBuilder<WCategory> entity)
        {
            entity.HasNoKey();

            entity.ToView("WCategory");

            entity.Property(e => e.Name).IsUnicode(false);

            entity.Property(e => e.UserModified).IsUnicode(false);
        }
    }
}
