// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using SportDatabase.Model;
using System;

namespace SportDatabase.Context
{
    public class WfullArticleConfiguration : IEntityTypeConfiguration<WFullArticle>
    {
        public void Configure(EntityTypeBuilder<WFullArticle> entity)
        {
            entity.HasNoKey();

            entity.ToView("WFullArticle");

            entity.Property(e => e.FirstName).IsUnicode(false);

            entity.Property(e => e.LastName).IsUnicode(false);

            entity.Property(e => e.Name).IsUnicode(false);

            entity.Property(e => e.Picture).IsFixedLength();
        }
    }
}
