// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using SportDatabase.Model;
using System;

namespace SportDatabase.Context
{
    public class WuserConfiguration : IEntityTypeConfiguration<WUser>
    {
        public void Configure(EntityTypeBuilder<WUser> entity)
        {
            entity.HasNoKey();

            entity.ToView("WUser");

            entity.Property(e => e.FirstName).IsUnicode(false);

            entity.Property(e => e.LastName).IsUnicode(false);

            entity.Property(e => e.Login).IsUnicode(false);

            entity.Property(e => e.NameRole).IsUnicode(false);
        }
    }
}
